language: python
python:
- 3.8
before_install:
- pip install poetry
install: pip install -U tox-travis
script: tox
before_deploy:
  poetry config pypi-token.pypi $PYPI_TOKEN
deploy:
  provider: script
  script: poetry publish --build
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: sugix/grovec_sv_solution
    python: 3.8
