language: python
python:
- 3.8
before_install:
- pip install poetry
install: pip install -U tox-travis
script: tox
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSW
- poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: sugix/grovec_sv_solution
    python: 3.8
env:
  global:
  - secure: rMPbMKHxMAnqqPGMJaohZIhcRwAGtJ8pptvrprD0TlOoWErVzKAFKKerth1QzGvK9pvOwgeEMikrTnciAKCy8V1cEmIICIKxJQ77sxadofpbk50Cjl2Pk2foa/fUl4yJgGlP6WgfV/mMTEfG3dKHZKObY7jkVGVsdfeOBlKciNfqJDSwF7NTnFyzShQVjYTQZOVPfqRqlCILpfoij4SahZ6iKDh+m9KYP/6rjXRdPf5C+GVYkaysP10+rVKcYSiEWpXv/M8mZW14K5vhr9RAcK/571Db0VM84oZCuRo1r64n0ilZtZjGcva2qcNILsTpZPuKSWo9exyjcekwtUX+2vyckxHKCfp2jHU0OwqK0FFTc2D46VG7C6oM6sf/vr14dhMXuB3FN+GLy68IQCHcFsXh7k2hjE9YrZvALl+KuWIx/kXovqOGpTwqjbBeXeyqhHvEZnxZGfieI1hnRIo+RiUa7rr3T3amO8FKEB/nbgM7ItcaeY16XwJJrxy4gKqMOuwz0BsFBt4WM4Wt7BZGELbpQH3bdZX/9ybG/TdTtJcML7PQ3UqlRz7AwEmHadAGxzxd/UDJCu/uOoWqDPvfT8BY3p25IgS61KSqftnAswpFkIs+RR87jiKbHp5Lv7hNaTZrXrnveboVh8C1dTJqNzj6X0XOpk5N4oMTwtRf2Xk=
  - secure: tHp8/o95I0jHgX1STFpn6bpgy7mEYKaG2zFJ2GcMB5hC8Ihi6JGDvK+gpKEZ89xC6gEGuDMpfPv/ZoHiUfDTtDWTdzAjvnLduAD1d9iu4wX6ekR5ud23/mQi/v17cdbEzWqBP+hTmHTeMDPF5GFJzEr4XrCE2zBcGv4qLRc4nLHn91HQBDWAAvgV5sGXHI+e7MIIcNVO6hmZJ0MUFhi/uRj+fbLZ9vbXswAbJ2A12UOGfS/Caj0OUYESNC4fUm3sFdG+yxeTaS5zGMuLFeZS+yQk5kVQY0chYIapNqHVrsN80hyQfH1/LEe+qE8vZArmX0m5pmtNlfnuT7RM6JPAigc3PeiOImZ1bdPB/bMEX8XVCx1iA7HU4pv/goRFlfrSvrmYdjsMZOPlm1jGhVugyejhBqiz/6vx3kJYTcyANlnfWzAenYlV5I2ATU/4H+SnSTxncj90jx0PFEE9zr8a6iRn892F+YgxfSQf9VpjbVVJOa+Lk9p+U8LfE8woXQnlbYyaFUpIidZcRD40QGlKmZM9cFWc8iuS7qe1v7Dtz57fIKPHaCsgZSeOQ8iWETdTlCyVNLmC8QOGTgWtQ6JdeJK5xTlqcI8eb07Gz7F2LexiZqhQ8o3q2WlxqQw6alsq7afvu/H1VvIBbzYqiHtM93EVotVb7/hDz7IR87s7RFM=
